# Site settings
name: Dahsoon
title: Dahsoon | An Internet Holding Company 
description: We devlope businesses around the internet.
url: https://dahsoon.github.io/
baseurl: ''
email: hi@dahsoon.com
cover: https://dahsoon.github.io/img/og.png
logo:  https://dahsoon.github.io/img/logo.png
resume: h
social:
  - title: email
    url: mailto:hi@dahsoon.com
  - title: twitter
    url: https://twitter.com/dahsoon
  - title: instagram
    url: https://instagram.com/dahsoon
  - title: codepen
    url: http://codepen.io/dahsoon
  - title: github
    url: https://github.com/dahsoon
  - title: linkedin
    url: https://www.linkedin.com/in/dahsoon

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
