# Site settings
name: microSEED
title: microSEED | Investments for Microbusinesses 
description: We invest in bootstrapped businesses and early stage startups.
url: https://microseedxyz.github.io/
baseurl: ''
email: hi@microseed.xyz
cover: https://microseedxyz.github.io/img/og.png
logo:  https://kismayomed.github.io/logo-update.png
resume: h
social:
  - title: email
    url: mailto:hi@microseed.xyz
  - title: twitter
    url: https://twitter.com/microseedxyz
  - title: instagram
    url: https://instagram.com/microseedxyz
  - title: codepen
    url: http://codepen.io/microseedxyz
  - title: github
    url: https://github.com/microseedxyz
  - title: linkedin
    url: https://www.linkedin.com/in/microseedxyz

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
